### ISSUE TITLE
About SimpleCIL

### ISSUE THREAD

**Issue by boringKey** [zhoudw-zdw/RevisitingCIL#11]
This is an excellent work on continual learning and PTM. However, I encountered a problem: when reproducing SimpleCIL, I was unable to achieve the results shown in the paper on CIFAR-100 (an average of 6% lower). I am not sure what is causing this issue and seek your advice. Thank you!

**Comment by zhoudw-zdw** [comment]
Thank you for your interest in our work. Please keep all package versions aligned with the readme file. If the problem still occurs, attach related logs, and we will find out the reason.

**Comment by zhoudw-zdw** [comment]
We've uploaded all training logs and corresponding jsons in the repo. You shall be able to reproduce those results as in our log.
