### ISSUE TITLE
Some questions about the implementation details of replay

### ISSUE THREAD

**Issue by SydCS** [zhoudw-zdw/RevisitingCIL#13]
Hi! Thank you for this great work.
I am a rookie in this field, and have some questions about the implementation details. 

1. What is the `"memory_size": 2000,
    "memory_per_class": 20,
    "fixed_memory": false,`  in config file for? From my understanding, this work doesn't include memory replay. Are they just some placeholders that have no use in this but play its part in other works under this PyCIL framework?
2. What is the `nme` classification accuracy? I know it stands for Nearest-Mean-of-Exemplars. But again, this work has no exemplars. Is it of no use either? And is the classifier always `cnn` where the fc layer is replaced with class prototypes？

Looking forward to your kind reply. Thank you in advance.

**Comment by zhoudw-zdw** [comment]
Hi, thank you for your interest.

1. Yes. Memory-related tokens are placeholders, and they are not used in this repo.
2. I think this repo does not print NME accuracy. See logs here https://github.com/zhoudw-zdw/RevisitingCIL/tree/main/logs
