### ISSUE TITLE
[ ObjectNet dataset ]

### ISSUE THREAD

**Issue by IemProg** [zhoudw-zdw/RevisitingCIL#2]
Hi,

Wonderful work, thanks for sharing the code. Could you please, share the script to split the original ObjectNet dataset into train, and test according to the filenames you provided?

Thanks !

**Comment by zhoudw-zdw** [comment]
Thanks for your interest in our work.

In fact, the ObjectNet subset is sampled from the original dataset, so we suggest you download the processed data.

Anyway, if you are going to use the file list, you should download the original dataset first and then process each line of the train/test list. Within each line, you should copy it from the source directory to the target directory. We will include a Python file for processing the data upon acceptance, so please stay tuned.

**Comment by zhoudw-zdw** [comment]
Hi,

It takes some time for the paper review, while finally it has been accepted by IJCV recently. Here is the code for data split with source data and file lists.

```
import os
import shutil

# Define file paths
test_file = 'test.txt'
source_dir = 'images'

# Read each line from the test.txt file
with open(test_file, 'r') as file:
    lines = file.readlines()

# Process each line
for line in lines:
    # Remove newline characters and leading/trailing spaces
    line = line.strip()
    
    # Parse the target directory and file name
    parts = line.split('/')
    category = parts[-2]  # Get the directory name after the second '/', e.g., "alarm_clock"
    file_name = parts[-1]  # Get the file name, e.g., "6f4cc5da3d2d4cc.png"
    
    # Construct the source file path
    source_file = os.path.join(source_dir, category, file_name)
    
    # Construct the target directory path
    target_dir = os.path.join('.', *parts[1:-1])  # ./test/air_freshener/ or ./test/alarm_clock/
    
    # Create the target directory if it does not exist
    os.makedirs(target_dir, exist_ok=True)
    
    # Copy the file to the target directory
    shutil.copy(source_file, os.path.join(target_dir, file_name))

print("File copying completed.")
```
