### ISSUE TITLE
md5sum check the dataset

### ISSUE THREAD

**Issue by qsunyuan** [zhoudw-zdw/RevisitingCIL#5]
Your work is truly inspiring.

For the dataset, I was wondering if the authors could provide the `md5sum` code  to ensure that I have downloaded it correctly.

Thx in advance.

**Comment by zhoudw-zdw** [comment]
Hi, thanks for your interest in our work. The md5sum information of these datasets is as below.


85e342a2d5f941e740193602057df7a5 *cub.zip
730aa3fb9c7d2ec0b6381c6b23040681 *imagenet-r.zip
7f4aaf0b1532b7a0bd670822c152d3c5 *ina.zip
f1c30808a707f9197c6c811ea52e5cbb *omnibenchmark.zip
a9c37bde6105a2516c900b0c33a437c1 *vtab.zip
63ff7443a47bd682016a8ec59b8cc1bc *objnet.tgz
