### ISSUE TITLE
huggingface cannot connection

### ISSUE THREAD

**Issue by 335812350** [zhoudw-zdw/RevisitingCIL#6]
Hi, thank you very much for your work. When I reproduce your code, I have the problem that Huggingface cannot connect, how can I solve this? Can you update the code to make it work?

**Comment by zhoudw-zdw** [comment]
Hi, I am not quite sure if this issue is related to this repo. Perhaps you need to open an issue at https://github.com/huggingface/huggingface_hub asking for help connecting a repo to huggingface.
