### ISSUE TITLE
About datasets Label names

### ISSUE THREAD

**Issue by DoubleClass** [zhoudw-zdw/RevisitingCIL#7]
Great work, thanks a lot for sharing your code.

**Comment by DoubleClass** [comment]
But I have some issues about the processed datasets. Like in VTAB, you only provide the 10-50 folder, I can't find the label name for each class.
Same for omnibenchmark datasets, I can only find the '4-303' folder, where can I find the label you sampled and used in this paper?
Thanks a lot!

**Comment by zhoudw-zdw** [comment]
Thanks for your interest in our work. Unfortunately, I also do not know the specific class name for them.

For VTAB, I have left the dataset order in the zip file, and you can retrieve the corresponding class name from the source dataset.

For Omnibenchmark, the class labels in the source dataset are named with numerical numbers, which do not have a class label. Hence, I also do not know the class names for them.
