### ISSUE TITLE
About datasets OmniBenchmark

### ISSUE THREAD

**Issue by DoubleClass** [zhoudw-zdw/RevisitingCIL#8]
I found that at least three same class are treated as different classes in you 300 train split:
![image](https://github.com/zhoudw-zdw/RevisitingCIL/assets/35952616/5a311231-1ca9-499f-928e-a938c6019ff5)
![image](https://github.com/zhoudw-zdw/RevisitingCIL/assets/35952616/4ffe21d5-d0a8-44bf-a632-4688d7dcd0eb)
![image](https://github.com/zhoudw-zdw/RevisitingCIL/assets/35952616/7f5a715f-0bc8-4755-8a70-24e5888c6d44)
![image](https://github.com/zhoudw-zdw/RevisitingCIL/assets/35952616/5d75b5bb-3fbf-4f2e-b73c-52064b6ab805)
the file name of the corresponding pictures are even the same. 
Why this happen?

**Comment by zhoudw-zdw** [comment]
The data selection process of Omnibenchmark is as follows:
1) Select the classes that have instances more than some threshold.
2) Randomly split instances into train and val.

Hence, if the images overlap, the reason may come from the source dataset. I would be grateful if you could check the source on omnibenchmark dataset to find if the overlap also exists, and I shall explain in the readme.
